# install OperatorResource to install:
# - cert-manager
# - istio
# - Kalm CRD & Roles
# - Kalm controller
# - Kalm dashboard
apiVersion: v1
kind: Namespace
metadata:
  name: kalm-operator
---
apiVersion: v1
kind: Namespace
metadata:
  name: kalm-system
  labels:
    istio-injection: enabled
    kalm-enabled: "true"
---
apiVersion: install.kalm.dev/v1alpha1
kind: KalmOperatorConfig
metadata:
  namespace: kalm-operator
  name: kalmoperatorconfig-sample
spec:
  kalmVersion: v0.1.0-rc.10
