
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.2.4
  creationTimestamp: null
  name: httpscerts.core.kalm.dev
spec:
  additionalPrinterColumns:
  - JSONPath: .status.conditions[0].status
    name: Ready
    type: string
  - JSONPath: .status.conditions[0].message
    name: Message
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: core.kalm.dev
  names:
    kind: HttpsCert
    listKind: HttpsCertList
    plural: httpscerts
    singular: httpscert
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: HttpsCert is the Schema for the httpscerts API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: HttpsCertSpec defines the desired state of HttpsCert
          properties:
            domains:
              items:
                type: string
              minItems: 1
              type: array
            httpsCertIssuer:
              type: string
            isSelfManaged:
              type: boolean
            selfManagedCertSecretName:
              type: string
          required:
          - domains
          type: object
        status:
          description: HttpsCertStatus defines the observed state of HttpsCert
          properties:
            conditions:
              items:
                properties:
                  message:
                    description: Message is a human readable description of the details
                      of the last transition, complementing reason.
                    type: string
                  reason:
                    description: Reason is a brief machine readable explanation for
                      the condition's last transition.
                    type: string
                  status:
                    description: Status of the condition, one of ('True', 'False',
                      'Unknown').
                    type: string
                  type:
                    description: Type of the condition, currently ('Ready').
                    type: string
                required:
                - status
                - type
                type: object
              type: array
            expireTimestamp:
              format: int64
              type: integer
            isSignedByTrustedCA:
              type: boolean
            wildcardCertDNSChallengeDomainMap:
              additionalProperties:
                type: string
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
