
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.2.4
  creationTimestamp: null
  name: rolebindings.core.kalm.dev
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.subject
    name: Subject
    type: string
  - JSONPath: .spec.creator
    name: Creator
    type: string
  - JSONPath: .spec.expiredAt
    name: ExpiredAt
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: core.kalm.dev
  names:
    kind: RoleBinding
    listKind: RoleBindingList
    plural: rolebindings
    singular: rolebinding
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: RoleBinding is the Schema for the deploykeys API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            creator:
              description: Creator of this binding
              minLength: 1
              type: string
            expiredAt:
              description: Expire time of this key. Infinity if blank
              format: date-time
              type: string
            role:
              enum:
              - viewer
              - editor
              - owner
              - clusterViewer
              - clusterEditor
              - clusterOwner
              - suspended
              - placeholder
              type: string
            subject:
              minLength: 1
              type: string
            subjectType:
              enum:
              - user
              - group
              type: string
          required:
          - creator
          - role
          - subject
          - subjectType
          type: object
        status:
          description: RoleBindingStatus defines the observed state of RoleBinding
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
