
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.2.4
  creationTimestamp: null
  name: httpscertissuers.core.kalm.dev
spec:
  group: core.kalm.dev
  names:
    kind: HttpsCertIssuer
    listKind: HttpsCertIssuerList
    plural: httpscertissuers
    singular: httpscertissuer
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: HttpsCertIssuer is the Schema for the httpscertissuers API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: HttpsCertIssuerSpec defines the desired state of HttpsCertIssuer
          properties:
            acmeCloudFlare:
              properties:
                apiTokenSecretName:
                  minLength: 1
                  type: string
                email:
                  minLength: 1
                  type: string
              required:
              - apiTokenSecretName
              - email
              type: object
            caForTest:
              type: object
            dns01:
              properties:
                configs:
                  additionalProperties:
                    properties:
                      allowfrom:
                        items:
                          type: string
                        type: array
                      fulldomain:
                        type: string
                      password:
                        type: string
                      subdomain:
                        type: string
                      username:
                        type: string
                    required:
                    - fulldomain
                    - password
                    - subdomain
                    - username
                    type: object
                  type: object
              required:
              - configs
              type: object
            http01:
              properties:
                email:
                  type: string
              type: object
          type: object
        status:
          description: HttpsCertIssuerStatus defines the observed state of HttpsCertIssuer
          properties:
            ok:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "make" to regenerate code after modifying
                this file'
              type: boolean
          required:
          - ok
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
