
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-core-kalm-dev-v1alpha1-accesstoken
  failurePolicy: Fail
  name: maccesstoken.kb.io
  rules:
  - apiGroups:
    - core.kalm.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - accesstokens
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-core-kalm-dev-v1alpha1-componentpluginbinding
  failurePolicy: Fail
  name: mcomponentpluginbinding.kb.io
  rules:
  - apiGroups:
    - core.kalm.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - componentpluginbindings
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-core-kalm-dev-v1alpha1-component
  failurePolicy: Fail
  name: mcomponent.kb.io
  rules:
  - apiGroups:
    - core.kalm.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - components
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-core-kalm-dev-v1alpha1-dockerregistry
  failurePolicy: Fail
  name: mdockerregistry.kb.io
  rules:
  - apiGroups:
    - core.kalm.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - dockerregistries
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-core-kalm-dev-v1alpha1-domain
  failurePolicy: Fail
  name: mdomain.kb.io
  rules:
  - apiGroups:
    - core.kalm.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - domains
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-core-kalm-dev-v1alpha1-httproute
  failurePolicy: Fail
  name: mhttproute.kb.io
  rules:
  - apiGroups:
    - core.kalm.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - httproutes
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-core-kalm-dev-v1alpha1-httpscert
  failurePolicy: Fail
  name: mhttpscert.kb.io
  rules:
  - apiGroups:
    - core.kalm.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - httpscerts
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-core-kalm-dev-v1alpha1-logsystem
  failurePolicy: Fail
  name: mlogsystem.kb.io
  rules:
  - apiGroups:
    - core.kalm.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - logsystems
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-core-v1alpha1-protectedendpoint
  failurePolicy: Fail
  name: mprotectedendpointtype.kb.io
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - protectedendpointtypes
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-core-kalm-dev-v1alpha1-rolebinding
  failurePolicy: Fail
  name: mrolebinding.kb.io
  rules:
  - apiGroups:
    - core.kalm.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - rolebindings
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-core-kalm-dev-v1alpha1-singlesignonconfig
  failurePolicy: Fail
  name: msinglesignonconfig.kb.io
  rules:
  - apiGroups:
    - core.kalm.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - singlesignonconfigs

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-core-kalm-dev-v1alpha1-accesstoken
  failurePolicy: Fail
  name: vaccesstoken.kb.io
  rules:
  - apiGroups:
    - core.kalm.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - accesstokens
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-core-kalm-dev-v1alpha1-acmeserver
  failurePolicy: Fail
  name: vacmeserver.kb.io
  rules:
  - apiGroups:
    - core.kalm.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - acmeservers
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-core-kalm-dev-v1alpha1-componentpluginbinding
  failurePolicy: Fail
  name: vcomponentpluginbinding.kb.io
  rules:
  - apiGroups:
    - core.kalm.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - componentpluginbindings
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-core-kalm-dev-v1alpha1-component
  failurePolicy: Fail
  name: vcomponent.kb.io
  rules:
  - apiGroups:
    - core.kalm.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - components
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-core-kalm-dev-v1alpha1-dockerregistry
  failurePolicy: Fail
  name: vdockerregistry.kb.io
  rules:
  - apiGroups:
    - core.kalm.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - dockerregistries
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-core-kalm-dev-v1alpha1-domain
  failurePolicy: Fail
  name: vdomain.kb.io
  rules:
  - apiGroups:
    - core.kalm.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - domains
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-core-kalm-dev-v1alpha1-httproute
  failurePolicy: Fail
  name: vhttproute.kb.io
  rules:
  - apiGroups:
    - core.kalm.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - httproutes
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-core-kalm-dev-v1alpha1-httpscert
  failurePolicy: Fail
  name: vhttpscert.kb.io
  rules:
  - apiGroups:
    - core.kalm.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - httpscerts
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-core-kalm-dev-v1alpha1-httpscertissuer
  failurePolicy: Fail
  name: vhttpscertissuer.kb.io
  rules:
  - apiGroups:
    - core.kalm.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - httpscertissuers
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-core-kalm-dev-v1alpha1-logsystem
  failurePolicy: Fail
  name: vlogsystem.kb.io
  rules:
  - apiGroups:
    - core.kalm.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - logsystems
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-core-v1alpha1-protectedendpoint
  failurePolicy: Fail
  name: vprotectedendpointtype.kb.io
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - protectedendpointtypes
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-core-kalm-dev-v1alpha1-rolebinding
  failurePolicy: Fail
  name: vrolebinding.kb.io
  rules:
  - apiGroups:
    - core.kalm.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - rolebindings
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-core-kalm-dev-v1alpha1-singlesignonconfig
  failurePolicy: Fail
  name: vsinglesignonconfig.kb.io
  rules:
  - apiGroups:
    - core.kalm.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - singlesignonconfigs
